# Generated by Django 2.1.4 on 2019-02-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='marks1',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='marks2',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='marks3',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='marks4',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='marks5',
        ),
        migrations.AddField(
            model_name='marks',
            name='marks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
